=== HADES-Cracovia/pandaweb/xml-db/database/TrbNet.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!--==============================
    Type Definitions
==============================-->
<xs:simpleType name="nametype">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9a-zA-Z_]+"/>
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="addresstype">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9a-fA-F]{4}"/>
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="valuetype">
  <xs:restriction base="xs:string">
    <xs:pattern value="[0-9a-fA-F]+"/>
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="modetype">
  <xs:restriction base="xs:string">
    <xs:pattern value="[rwb]+"/>
    <!-- (r)ead and /or (w)rite, plus maybe (b)lock, if a no-more-data from this registers transports some vital information-->
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="functiontype">
 <xs:restriction base="xs:string">
      <xs:enumeration value="config"/>
      <xs:enumeration value="trigger"/>
      <xs:enumeration value="status"/>
      <xs:enumeration value="statistics"/>
    </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="bittype">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="31"/>
  </xs:restriction>
</xs:simpleType> 

<xs:simpleType name="formattype">
 <xs:restriction base="xs:string">
    <xs:enumeration value="integer"/>
    <xs:enumeration value="signed"/>
    <xs:enumeration value="unsigned"/>
    <xs:enumeration value="hex"/>
    <xs:enumeration value="bitmask"/>
    <xs:enumeration value="boolean"/>
    <xs:enumeration value="time"/>
    <xs:enumeration value="string"/>
  </xs:restriction>
</xs:simpleType> 


<!--==============================
    Attribute Definition
==============================-->
<xs:attribute name="name"         type="nametype" />
<xs:attribute name="address"      type="addresstype" />
<xs:attribute name="offset"       type="addresstype" />
<xs:attribute name="mode"         type="modetype"  />
<xs:attribute name="type"         type="functiontype" />
<xs:attribute name="function"     type="functiontype" />
<xs:attribute name="start"        type="bittype" />
<xs:attribute name="size"         type="xs:positiveInteger" />
<xs:attribute name="defaultValue" type="valuetype" />
<xs:attribute name="value"        type="valuetype" />
<xs:attribute name="format"       type="formattype" />
<xs:attribute name="continuous"   type="xs:boolean" />


<!--==============================
    Simple Elements
==============================-->
<xs:element name="description" type="xs:string" />

<!--==============================
    Complex Elements
==============================-->
<xs:element name="TrbNet">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
      <xs:element   ref="group"       maxOccurs="unbounded" />
      <xs:element   ref="register"    maxOccurs="unbounded" />
      <xs:element   ref="memory"      maxOccurs="unbounded" />
      <xs:element   ref="fifo"        maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute ref="name" />
    <xs:attribute ref="offset" />
  </xs:complexType>
</xs:element>

<xs:element name="group">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element   ref="group"       maxOccurs="unbounded" />
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
      <xs:element   ref="register"    maxOccurs="unbounded" />
      <xs:element   ref="memory"      maxOccurs="unbounded" />
      <xs:element   ref="fifo"        maxOccurs="unbounded" />
    </xs:choice>
    <xs:attribute ref="name" use="required" />
    <xs:attribute ref="address" />
    <xs:attribute ref="size" />
    <xs:attribute ref="function" />
    <xs:attribute ref="continuous" />
    <xs:attribute ref="defaultValue" />
    <xs:attribute ref="format" />
  </xs:complexType>
</xs:element> 


<xs:element name="field">
  <xs:complexType>
    <xs:all>
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
    </xs:all>
    <xs:attribute ref="name" />
    <xs:attribute ref="start" />
    <xs:attribute ref="size" />
    <xs:attribute ref="type" />
    <xs:attribute ref="mode" />
    <xs:attribute ref="defaultValue" />
    <xs:attribute ref="format" />
  </xs:complexType>
</xs:element> 


<xs:element name="register">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element   ref="field" />
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
    </xs:choice>
    <xs:attribute ref="name" />
    <xs:attribute ref="address" />
    <xs:attribute ref="mode" />
    <xs:attribute ref="function" />
  </xs:complexType>
</xs:element> 

<xs:element name="memory">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element   ref="field" />
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
    </xs:choice>
    <xs:attribute ref="name" />
    <xs:attribute ref="address" />
    <xs:attribute ref="size" />
    <xs:attribute ref="mode" />
    <xs:attribute ref="function" />
  </xs:complexType>
</xs:element> 

<xs:element name="fifo">
  <xs:complexType>
    <xs:choice maxOccurs="unbounded">
      <xs:element   ref="field" />
      <xs:element   ref="description" minOccurs="1" maxOccurs="1" />
    </xs:choice>
    <xs:attribute ref="name" />
    <xs:attribute ref="address" />
    <xs:attribute ref="mode" />
    <xs:attribute ref="function" />
  </xs:complexType>
</xs:element> 


</xs:schema>

=== HADES-Cracovia/pandaweb/xml-db/database/jtag_registers_SPEC.xml
<?xml version="1.0"  encoding="utf-8" ?>
<TrbNet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="TrbNet.xsd"
  name="JtagController"
  offset="1000"
  >
<group name="JtagCommonControl"
       address="0000"  size="21"  function="config"  continuous="true">

  <register name="WaitBeforeStart"
            address="0007" mode="rw" function ="config" >
    <description>Wait time between write sequence and start signal.</description>
    <field name="WaitBeforeStart"
           start="0"   size="20"  mode="rw"  type="config"  format="integer"  defaultValue="0" >
      <description>The number of MAPS clock cycles to wait after last write before sending the start signal. </description>
    </field>
  </register>
  
  <register name="TriggerInitSeq"
            address="000c" mode="w" function ="trigger" >
    <description>Trigger the init sequence.</description>
    <field name="TriggerInitSeq"
           start="0"   size="5"  mode="w"  type="trigger"  format="bitmask"  defaultValue="0" >
      <description>A bitmask to trigger the init sequence on individual JTAG chains. </description>
    </field>
  </register>

  <register name="TriggerReset"
            address="000d" mode="w" function ="trigger" >
    <description>Trigger the init sequence.</description>
    <field name="TriggerReset"
           start="0"   size="5"  mode="w"  type="trigger"  format="bitmask"  defaultValue="0" >
      <description>A bitmask to trigger sending a reset pulse on individual JTAG chains </description>
    </field>
  </register>

  <register name="TriggerStart"
            address="000e" mode="w" function ="trigger" >
    <description>Trigger sending a start pulse.</description>
    <field name="TriggerStart"
           start="0"   size="5"  mode="w"  type="trigger"  format="bitmask"  defaultValue="0" >
      <description>A bitmask to trigger sending a start pulse on individual JTAG chains </description>
    </field>
  </register>

  <register name="TriggerJtagRun"
            address="000f" mode="w" function ="trigger" >
    <description>Trigger running JTAG write.</description>
    <field name="TriggerJtagRun"
           start="0"   size="5"  mode="w"  type="trigger"  format="bitmask"  defaultValue="0" >
      <description>A bitmask to trigger writing the JTAG registers three times on individual JTAG chains </description>
    </field>
  </register>

  <register name="ResetBeforeInit"
            address="0010" mode="rw" function ="config" >
    <description>Generate a reset before doing init sequence</description>
    <field name="ResetBeforeInit"
           start="0"   size="1"  mode="rw"  type="config"  format="boolean"  defaultValue="0" >
      <description>Enable to send a reset pulse before starting init sequence</description>
    </field>
  </register>

  <register name="ResetAfterFirstWrite"
            address="0011" mode="rw" function ="config" >
    <description>Generate a reset after first register write sequence</description>
    <field name="ResetAfterFirstWrite"
           start="0"   size="1"  mode="rw"  type="config"  format="boolean"  defaultValue="0" >
      <description>Enable to send a reset pulse after the first writing of JTAG registers</description>
    </field>
  </register>

  <register name="TriggerWriteOnce"
            address="0014" mode="w" function ="trigger" >
    <description>Trigger writing all JTAG registers once</description>
    <field name="TriggerWriteOnce"
           start="0"   size="5"  mode="w"  type="trigger"  format="bitmask"  defaultValue="0" >
      <description>Trigger writing all JTAG registers once on individual JTAG chains</description>
    </field>
  </register>


</group>

</TrbNet>
